### ISSUE TITLE
More pieces by default in package

### ISSUE THREAD

**Issue by 9glenda** [MDLC01/board-n-pieces#2]
you can use the lichess pieces from [here](https://github.com/lichess-org/lila/tree/master/public/piece). I know you can include custom ones but having the lichess pieces by default is a good idea in my opinion. 
If you disagree you can just close the issue it's not of high priority to me.

**Comment by MDLC01** [comment]
I don't want to add too many piece sets because this will increase the package size. Also, anything I include should be available under an open source license. Are there specific sets you want to see included by default?

**Comment by MDLC01** [comment]
I'm closing this issue as not planned because I don't want to add too many other sets in order to keep the package size low. Only adding a few sets is pointless, since it makes it unlikely for users to find what they want. Most people will be fine with the current default, and the few who want another set can easily import it themselves.
